[preface]
== Antes de começar é importante ler essa parte...

//[NOTE]
//Esse material é usado como apoio às aulas da disciplina de Testes de _software_
//do Curso Superior de Tecnologia em Sistemas para WEB do Instituto Federal de Educação,
//Ciência e Tecnologia do Tocantins - IFTO. Ele não substitui livros técnicos ou
//outras fontes. Ele é apenas um resumo para auxiliar o estudante.

=== Qual o propósito deste material
Este material de apoio é destinado inicialmente aos estudantes do curso Superior de Tecnologia em Sistemas para Internet (CSTSI) do Instituto Federal de Educação, Ciência e Tecnologia do Tocantins, mas também pode ser usado por discentes de outros cursos tais como Ciência da Computação, Sistemas de Informação, Engenharia da Computação e Engenharia de Software. Ele tem o objetivo de apresentar os principais conceitos relacionados a testes de software, seus níveis, seus objetivos, como os testes são projetados e executados. De forma esse material pretensão de cobrir todos os assuntos relacionados à área de testes, que é muito extensa. Ele também não substitui livros de Engenharia de Software ou outros livros técnicos relacionados. A proposta é que ele sirva como um guia inicial para aqueles que estão dando os primeiros passos nessa área que é tão importante para o desenvolvimento de _software_.


[TIP]
Procure por outras fontes para complementar esse material. Um bom lugar para começar
é o site link:https://www.infoq.com/br/[INFOQ] que traz palestras e artigos atualizados relacionados a
diversos aspectos da engenharia de _software_.


=== Como o material está organizado
É importante lembrar que o presente material foi construído com o intuito prioritário
de atender ao CSTSI. Assim, as buscas por conteúdo foram feitas para atender a :link:http://www.ifto.edu.br/palmas/campus-palmas/cursos/graduacao/tecnologico/sistemas-para-internet/copy_of_grade-curricular/grade-curricular-bacharelado-em-engenharia-civil.pdf/view/[ementa da disciplina que está em vigor], que é mostrada a seguir:

- Conceitos básicos relacionados a teste de software;
- Processos de testes;
- Ferramentas para planejamento, elaboração e automatização testes de software;
- Manipular ferramentas para execução de planos de testes de software;
- Classes de automação: QAI x ISTQB;
- Gerenciamento do planejamento de testes;
- Projeto de Casos de Teste;
- Tipos de Testes;
- Ferramentas;
- Gerenciamento dos defeitos;
- Elaboração de laudo e parecer técnico.

Com base nisso, o conteúdo disponível nesse material está assim dividido:

- O capitulo <<Revisão>> tem o objetivo de posicionar as atividades de teste de software dentre as demais atividades básicas do ciclo de desenvolvimento de software.
As interações entre o teste e análise, projeto e implementação são apresentadas com o objetivo de auxiliar o estudante em um primeiro contato e entender em que momento elas ocorrem. Trata-se de capitulo informativo que não está relacionado diretamente com a ementa do curso.

- O capitulo <<queeteste>> apresenta o conceito sobre teste e reforça sua importância na obtenção de um software que atenda melhor aos requisitos do cliente e que seja construído da melhor forma possível. Aqui é onde o estudo relativo aos testes começa de fato.

//A disciplina de testes de software tem o objetivo de

//É recomendado que o estudante, que não se limite à leitura e ao conteúdo deste material. Pesquise na internet outros materiais e leia outros livros e faça todos os exercícios propostos. Programação, assim como matemática, requer muito exercício, muita prática. Como mencionado anteriormente, a programação de computadores é uma das subáreas mais importantes da carreira que você escolheu seguir. Boa parte das disciplinas do seu curso depende do conhecimento adquirido em Introdução à Programação. Portanto, dedique o máximo que puder ao aprendizado de uma área que vai permiti-lo transformar sonhos em realidade.


=== Público alvo

O público alvo desse livro, conforme mencionado anteriormente, são os estudantes do Curso Superior de Técnologia em Sistemas para Internet do Instituto Federal de Eucação, Ciência e Tecnologia do Tocantins, na modalidade presencial. Ele pode ser usado por outros cursos em que os estudantes tenham tido contato com disciplinas de Análise e Projeto de sistemas, introdução a programação ou programação para WEB.

[[como_estudar]]
=== Como você deve estudar cada capítulo

* Leia a visão geral do capítulo
* Estude os conteúdos das seções
* Realize as atividades no final do capítulo
* Verifique se você atingiu os objetivos do capítulo

.Na sala de aula do curso
* Tire dúvidas e discuta sobre as atividades do livro com outros integrantes do curso
* Leia materiais complementares eventualmente disponibilizados
* Realize as atividades propostas pelo professor da disciplina

// Sempre manter uma linha em branco no final
