== Testes A/B

=== O que é teste A/B ?

O teste A/B, consiste em criar duas versões do objeto a ser testado, seja esse objeto emails, Landing Pages, dentre outros exemplos. A primeira é a versão original; já a segunda, é mais desafiadora, com modificações. Depois, elas são mostradas para o mesmo número de pessoas e comparadas. Por fim, verifica-se qual tem mais eficiência.

Os testes A/B testam apenas uma variável (duas variações) de cada vez com o objetivo de escolher a melhor entre as duas. Os testes eliminam a necessidade de fazer suposições e permitem que você tome decisões baseadas em números, o que diminui a chance da sua decisão resultar em falhas no futuro.

=== Por que fazer testes A/B

O teste A / B permite que você tire mais proveito do tráfego existente. Embora o custo de aquisição de tráfego pago possa ser enorme, o custo de aumentar suas conversões é mínimo. Para comparar, um Small Business Plan do Visual Website Optimizer começa em US $ 49. Esse é o custo de 5 a 10 cliques no Google Adwords. O retorno do investimento do teste A / B pode ser enorme, pois mesmo pequenas alterações em uma _Landing Page_ ou site podem resultar em aumentos significativos nos leads gerados, nas vendas e na receita.

=== Onde aplicar o teste A/B?

Os testes A/B devem ser aplicados em situações em que há a necessidade ou o potencial de otimizar alguma métrica importante para a empresa, sejam acessos, aberturas, cliques, geração de Leads etc.
Por exemplo, se você possui um email cuja taxa de cliques está muito baixa, ou uma Landing Page com baixa taxa de conversão, vale a pena criar uma segunda versão para rodar um teste A/B e descobrir se a nova versão tem um desempenho melhor.

=== Como executar um Teste A/B
// Essa parte foi copiada desse site
//https://vwo.com/ab-testing/
. Estude seus dados de website: use uma ferramenta de análise de website, como o Google Analytics, e encontre as áreas problemáticas em seu funil de conversão. Por exemplo, você pode identificar as páginas com a maior taxa de rejeição. Digamos que sua página inicial tenha uma taxa de rejeição excepcionalmente alta.

. Observe o comportamento do usuário: utilize as ferramentas de análise de comportamento do visitante, como heatmaps, gravações de visitantes, análise de formulários e pesquisas na página, e descubra o que está impedindo a conversão dos visitantes. Por exemplo, "O botão de CTA não é proeminente na home page".

. Construir uma hipótese: de acordo com as percepções das ferramentas de análise do comportamento do visitante, construa uma hipótese destinada a aumentar as conversões. Por exemplo, "Aumentar o tamanho do botão de CTA o tornará mais proeminente e aumentará as conversões".

. Teste sua hipótese: crie uma variação de acordo com sua hipótese e teste A / B contra a página original. Por exemplo, "A / B teste sua página inicial original em relação a uma versão que tenha um botão CTA maior". Calcule a duração do teste em relação ao número de visitantes mensais, taxa de conversão atual e a mudança esperada na taxa de conversão. (Use nossa Calculadora Bayesiana aqui.)

. Analise dados de teste e conclua conclusões: analise os resultados dos testes A / B e veja qual variação gerou as conversões mais altas. Se houver um vencedor claro entre as variações, prossiga com sua implementação. Se o teste permanecer inconclusivo, volte ao passo número três e refaça sua hipótese.

. Relate os resultados para todos os interessados: permita que outras pessoas em Marketing, TI e UI / UX conheçam os resultados do teste e as informações geradas.


//https://www.optimizely.com/optimization-glossary/ab-testing/


//Um how to sobre o Google Analytics
//https://www.crazyegg.com/blog/best-testing-software/
